semi: false
singleQuote: true
arrowParens: 'always'
requirePragma: false
trailingComma: 'none'
organizeImportsSkipDestructiveCodeActions: true
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - <THIRD_PARTY_MODULES>
  - ^[./]
